# services:
#   backend:
#     build: ./backend
#     ports:
#       - "4000:4000"
#     volumes:
#       - ./backend:/app
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#     volumes:
#       - ./frontend:/app
#     environment:
#       - REACT_APP_API_URL=http://localhost:8000   