version: "3"
services:
  backend:
    build: ./backend
    image: qcode-backend:latest
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=${MONGO_URI}
      - SECRET=${SECRET}
      - CORS_ORIGIN=http://localhost:3000
    restart: always

  frontend:
    build: ./frontend
    image: qcode-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
