services:
  backend:
    build: ./backend
    container_name: qcode-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb+srv://admin:admin@cluster0.b775wno.mongodb.net/?retryWrites=true&w=majority
      - SECRET=your_very_long_and_secure_secret_key_here
      - CORS_ORIGIN=http://localhost:3000
    restart: always
    networks:
      - qcode-network

  frontend:
    build: ./frontend
    container_name: qcode-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    restart: always
    networks:
      - qcode-network

networks:
  qcode-network:
    driver: bridge
