---
- name: Deploy QCode Application
  hosts: qcode
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-docker
          - docker-compose
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: /home/ubuntu/qcode
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Create docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: /home/ubuntu/qcode/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Pull Docker images
      docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - "{{ docker_registry }}/qcode-backend:latest"
        - "{{ docker_registry }}/qcode-frontend:latest"

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reset ssh connection to allow user changes to affect the current session
      meta: reset_connection

    - name: Run docker-compose
      become: true
      become_user: ubuntu
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/qcode

    - name: Verify containers are running
      become_user: ubuntu
      command: docker ps
      args:
        chdir: /home/ubuntu/qcode
      register: docker_ps_result

    - name: Show running containers
      debug:
        var: docker_ps_result.stdout_lines
